using System.ComponentModel;
using System.Globalization;
using System.Resources;

namespace Fenestra.Windows.Localization;

/// <summary>
/// Singleton source for UI localization bindings. Holds a map of named
/// <see cref="ResourceManager"/> instances and exposes a bindable 2-arg indexer
/// <c>this[resource, key]</c> that looks up strings using
/// <see cref="CultureInfo.CurrentUICulture"/>.
///
/// <para>
/// Framework-agnostic — lives in <c>Fenestra.Windows</c> and depends only on BCL types
/// (<see cref="ResourceManager"/>, <see cref="INotifyPropertyChanged"/>). WPF consumers
/// pair it with <c>Fenestra.Wpf.Localization.TrExtension</c> to get
/// <c>{fenestra:Tr messages, Greeting}</c> in XAML; WinForms or console consumers can
/// access the indexer directly or wrap it.
/// </para>
///
/// <para>
/// Typical wiring at startup:
/// </para>
/// <code>
/// TranslationSource.Instance.AddResourceManager(
///     "messages",
///     new ResourceManager("MyApp.Resources.Messages", typeof(App).Assembly));
///
/// TranslationSource.Instance.AddResourceManager(
///     "errors",
///     new ResourceManager("MyApp.Resources.Errors", typeof(App).Assembly));
///
/// localization.CultureChanged += (_, _) =&gt; TranslationSource.Instance.Invalidate();
/// </code>
/// </summary>
public sealed class TranslationSource : INotifyPropertyChanged
{
    /// <summary>Process-wide singleton. All bindings go through this instance.</summary>
    public static TranslationSource Instance { get; } = new();

    private readonly Dictionary<string, ResourceManager> _resourceManagers
        = new(StringComparer.OrdinalIgnoreCase);
    private readonly object _lock = new();

    public event PropertyChangedEventHandler? PropertyChanged;

    /// <summary>
    /// 2-arg indexer used by XAML bindings generated by <c>TrExtension</c>. Looks up
    /// <paramref name="key"/> in the <see cref="ResourceManager"/> previously registered
    /// under <paramref name="resource"/>.
    ///
    /// <para>
    /// Returns the key itself when either the resource name is not registered or the key
    /// is not found — useful during development so missing translations are visible in
    /// the UI instead of appearing as blank labels.
    /// </para>
    /// </summary>
    public string this[string resource, string key]
    {
        get
        {
            if (string.IsNullOrEmpty(key)) return string.Empty;
            if (string.IsNullOrEmpty(resource)) return key;

            ResourceManager? rm;
            lock (_lock)
            {
                _resourceManagers.TryGetValue(resource, out rm);
            }

            if (rm is null) return key;

            try
            {
                var value = rm.GetString(key, CultureInfo.CurrentUICulture);
                if (value is not null) return value;
            }
            catch
            {
                // Swallow per-manager errors (e.g., corrupted satellite assembly) and
                // fall through to the key fallback.
            }

            return key;
        }
    }

    /// <summary>
    /// Registers a <see cref="ResourceManager"/> under the given name. Call once per
    /// <c>.resx</c> file family your app uses. Re-registering the same name replaces
    /// the previous manager.
    /// </summary>
    public void AddResourceManager(string name, ResourceManager manager)
    {
        if (string.IsNullOrWhiteSpace(name))
            throw new ArgumentException("Resource name is required.", nameof(name));
        if (manager is null) throw new ArgumentNullException(nameof(manager));

        lock (_lock)
        {
            _resourceManagers[name] = manager;
        }
    }

    public bool HasResourceManager(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
            return false;

        lock (_lock)
        {
            return _resourceManagers.ContainsKey(name);
        }
    }

    /// <summary>
    /// Removes a previously registered <see cref="ResourceManager"/> by name.
    /// Returns <c>true</c> if the name was registered and removed.
    /// </summary>
    public bool RemoveResourceManager(string name)
    {
        if (string.IsNullOrWhiteSpace(name)) return false;

        lock (_lock)
        {
            return _resourceManagers.Remove(name);
        }
    }

    /// <summary>
    /// Clears all registered ResourceManagers. Primarily useful for tests.
    /// </summary>
    public void ClearResourceManagers()
    {
        lock (_lock)
        {
            _resourceManagers.Clear();
        }
    }

    /// <summary>
    /// Raises <see cref="PropertyChanged"/> with the magic name <c>"Item[]"</c>, which
    /// tells WPF (and other bindable consumers) to re-evaluate every binding that goes
    /// through this source's indexer. Call this whenever the UI culture changes —
    /// typically from <c>ILocalizationService.CultureChanged</c>.
    /// </summary>
    public void Invalidate()
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item[]"));
    }
}
